@startuml

title __HELPER's Class Diagram__\n

  namespace  {
    namespace baldr2.helper {
      class kbaldr2.helper.Alerts {
          {static} + showAlert()
          {static} + showConfirmationDialog()
          {static} + showWarning()
      }
    }
  }
  

  namespace  {
    namespace baldr2.helper {
      class kbaldr2.helper.Formatter {
          {static} - TIME_FORMATTER : DateTimeFormatter
          {static} + ESTtoLocal()
          {static} + UTCtoLocal()
          {static} + formatTime()
          {static} + localToUTC()
          {static} + parseTime()
      }
    }
  }
  

  namespace  {
    namespace baldr2.helper {
      class kbaldr2.helper.ObjectSearchUtil {
          {static} + searchObjectFields()
      }
    }
  }
  

  namespace  {
    namespace baldr2.helper {
      class kbaldr2.helper.SceneManager {
          {static} - appointmentReportStage : Stage
          {static} - appointmentStage : Stage
          {static} - countReportStage : Stage
          {static} - customerStage : Stage
          {static} - dashboardStage : Stage
          {static} - loginStage : Stage
          {static} - scheduleReportStage : Stage
          {static} + buildAppointmentScene()
          {static} + buildCustomerScene()
          {static} + buildDashboardScene()
          {static} + buildLoginScene()
          {static} + buildReportScene()
          {static} + getAppointmentController()
          {static} + getCustomerController()
          {static} + getStage()
          - SceneManager()
      }
    }
  }
  

  namespace  {
    namespace baldr2.helper {
      class kbaldr2.helper.TableFormatter {
          {static} - app_AppointmentIdCol : TableColumn<DataCache, Integer>
          {static} - app_ContactCol : TableColumn<DataCache, String>
          {static} - app_CustomerIdCol : TableColumn<DataCache, Integer>
          {static} - app_DescriptionCol : TableColumn<DataCache, String>
          {static} - app_EndDateAndTimeCol : TableColumn<DataCache, LocalDateTime>
          {static} - app_LocationCol : TableColumn<DataCache, String>
          {static} - app_StartDateAndTimeCol : TableColumn<DataCache, LocalDateTime>
          {static} - app_TitleCol : TableColumn<DataCache, String>
          {static} - app_TypeCol : TableColumn<DataCache, String>
          {static} - app_UserIdCol : TableColumn<DataCache, Integer>
          {static} - cust_AddressCol : TableColumn<DataCache, String>
          {static} - cust_CustIdCol : TableColumn<DataCache, Integer>
          {static} - cust_DivisionIdCol : TableColumn<DataCache, Integer>
          {static} - cust_NameCol : TableColumn<DataCache, String>
          {static} - cust_PhoneCol : TableColumn<DataCache, String>
          {static} - cust_PostalCol : TableColumn<DataCache, String>
          {static} - dataCacheTable : TableView<DataCache>
          {static} + buildAppTables()
          {static} + buildCustTables()
          {static} + setTableView()
      }
    }
  }
  



right footer


PlantUML diagram generated by SketchIt! (https://bitbucket.org/pmesmeur/sketch.it)
For more information about this tool, please contact philippe.mesmeur@gmail.com
endfooter

@enduml
